# -*- coding: utf-8 -*-
"""exam06_pandas01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t9E3Hvx1hR2_duKjAe2JT-3oDBiu7j6K

#Pandas 실습

##DataFrame
"""

import pandas as pd

df = pd.DataFrame([[15, '남', '영훈중'],
                   [17, '여', '성암중']],
                  index=['서준', '동연'],
                  columns=['나이', '성별', '학교'])
print(df)


df.index

df.columns

df = df.rename(index={'서준':'학생1', '동연':'학생2'})
df

df = df.rename(columns={'나이':'연령'})
df

df1 = df['연령']
print(df1)

print(type(df1))

df2 = df[['연령']]
print(type(df2))
print(df2)

df3 = df.iloc[0]
df3

print(type(df3))

df4 = df.loc['학생1']
df4

df.iloc[0, 0:2]

df.loc['학생1', '연령':'성별']

df.loc['학생3'] = [18, '남', '신일중']
df.loc['학생4'] = [14, '여', '풍문중']
df

df1 = df.drop(['학생3'], inplace=False, axis='rows')
print(df1)

df

df['학년'] = 3
df

df['키'] = [175, 180, 185, 190]
df

df1 = df.drop(['학년'], axis='columns', inplace=False)
df1

df

df1 = df[['연령', '성별', '학교', '키']]
df1

exam_data = {'이름':['경석', '연주', '선희'],
             '수학':[90, 85, 70],
             '영어':[98, 88, 78],
             '음악':[90, 89, 88],
             '체육':[88, 78, 69]}
df = pd.DataFrame(exam_data)
df.set_index('이름', inplace=True)
df

df.shape

df.iloc[0, 3] = 90
df

df.loc['경석', '체육'] = 100
df

df.loc['경석', ['영어', '체육']] = 120, 130
df

df = df.transpose()
df

df = df.T
df

df.loc['선희', '음악'] = 89
df

ndf1 = df.set_index('음악')
ndf1

ndf1.loc[89]

ndf2 = df.set_index(['음악', '수학'])
ndf2

ndf2.loc[(89, 70)]

ndf2.iloc[1]

ndf3 = df.reset_index().set_index(['음악'])
ndf3

ndf = df.reindex(list(df.index) + ['덕유', '영림'], fill_value=0)
ndf

df

ndf = df.sort_index(ascending=False)
ndf

ndf = df.sort_values(by='영어', ascending=False)
ndf

list(df.columns)

columns = list(df.columns)
columns.sort()

ndf = df[columns]
ndf

sr = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
sr

sr[1]

student1 = pd.Series({'국어':20, '영어':90})
student1

percentage = student1 / 100
percentage

student2 = pd.Series({'영어':40, '국어':80, '수학':80})
student2

student1 + student2

sr1 = student1.add(student2, fill_value=0)
sr1

df

ndf = df + 100
ndf

ndf2 = ndf - df
ndf2

df

df.to_csv('./df_sample.csv')

df1 = pd.read_csv('./df_sample.csv', index_col='이름')
df1

df1 = pd.read_csv('./df_sample.csv')
df1

df1.to_csv('./df_sample2.csv', index=False)

df2 = pd.read_csv('./df_sample2.csv', index_col=0)
df2

# df2 = df2.set_index('Unnamed: 0')
# df2

df

df.to_json('./df_sample.json', force_ascii=False)

ndf1 = pd.read_json('./df_sample.json')
ndf1

df.to_excel('./df_sample.xlsx')

df2 = pd.read_excel('./df_sample.xlsx', index_col=0)
df2

tables = pd.read_html('https://www.w3schools.com/html/html_tables.asp')
print(type(tables))
print(len(tables))
print(tables[0])

tables[1]

